---
title: "Factoraje Financiero"
author: "
Carmen Yaxiri Lopez Garcia
- Alexa Moreno Lopez
- Cristina Calderon Avalos
- Fernando Zuriel Martinez Barrera
- Juan Pablo Tellez Marquez
- Luis Eduardo Urquiza Hernandez
- Humberto Cortez Vazquez
- Leonardo Daniel Godinez Guizar"
format: html
editor: visual
---

```{=html}
<style>
body {
  font-family: Arial, sans-serif;
}
</style>
```
## Introduccion

En el mundo de las finanzas, existen diversas herramientas que las empresas pueden utilizar para gestionar su flujo de efectivo y asegurar su estabilidad financiera. Una de estas herramientas es el FACTORAJE FINANCIERO y durante este escrito se describirá lo que es el <u>*“Factoraje Financiero”*</u> y se les dará respuesta a las preguntas: **“¿Qué es?”**, **“¿Cómo funciona?”** y **“¿Como se debe o puede usar?**

## Antecedentes

El factoraje financiero, también conocido como factoring, es un servicio financiero que tiene sus raíces en la antigüedad. Sus orígenes se remontan a la época de los fenicios y babilonios, quienes implementaron formas tempranas de factoraje como un método para facilitar el comercio y la financiación de mercancías. En el mundo antiguo, los comerciantes vendían sus cuentas por cobrar a cambio de dinero en efectivo inmediato, una práctica que ayudaba a mantener el flujo de caja y a mitigar los riesgos asociados con el comercio a larga distancia.

Durante la Edad Media, el factoraje se consolidó en Europa, particularmente en Inglaterra, donde se utilizó extensamente en el comercio textil. Los **“factors”** o **“factores”** actuaban como intermediarios entre los productores y los compradores, ofreciendo adelantos sobre las ventas futuras de bienes. Este sistema permitió a los comerciantes y fabricantes obtener el capital necesario para continuar sus operaciones sin tener que esperar a que los compradores pagaran las mercancías.

El siglo XIX marcó un periodo de evolución significativa para el factoraje con la Revolución Industrial. En esta era, el comercio y la producción en masa crecieron a un ritmo acelerado, lo que aumentó la demanda de servicios financieros más sofisticados. El factoraje se adaptó a estas necesidades, evolucionando para incluir servicios adicionales como la gestión de cuentas por cobrar y la protección contra el riesgo de crédito desde finales de la década de los 80 se ha ido colándose poco a poco en la vida de los empresarios como una eficiente ayuda a su negocio.

En esencia, el “factoring” o “factoraje” implica la venta de facturas pendientes de pago a una entidad financiera o a una empresa de factoraje. A cambio, la empresa recibe un adelanto de efectivo por el valor de esas facturas, lo que le permite disponer de fondos de inmediato en lugar de esperar a que sus clientes paguen en el plazo establecido.

# Que es el Factoraje Financiero

El factoraje financiero es un instrumento de financiación a corto plazo, que utilizan las empresas como estrategia alternativa que permite disponer anticipadamente de las cuentas por cobrar para mejorar su liquidez y se puedan gestionar de manera más eficaz.

Este proceso es especialmente útil para las empresas que enfrentan dificultades para cobrar sus cuentas pendientes a tiempo, lo que puede afectar su flujo de efectivo y su capacidad para cubrir gastos operativos y financieros. El factoring financiero proporciona una fuente de financiamiento rápido y flexible sin incurrir en deudas adicionales.

El Factoraje o Factoring internacional se celebra a través de un contrato entre la empresa de Factoring (Factor) y el proveedor conforme al cual: El proveedor (supplier) cede al Factor los derechos que surgen de sus contratos de compraventa internacionales celebrados con sus clientes, excepto aquellos que se refieren a mercaderías compradas principalmente para su uso personal, familiar o doméstico. El Factor deberá realizar al menos dos de las siguientes funciones:

### Financiamiento al proveedor.

-   Administración del portafolio

-   Cobranza de las cuentas por cobrar

-   Cobertura contra el riesgo de no pago de los compradores.

Además, la cesión de las cuentas por cobrar deberá ser notificada por escrito al comprador (deudor). Definición de acuerdo con la Convención UNIDROIT (El Instituto Internacional para la Unificación del Derecho Privado).

### ¿Cuáles son los servicios del Factoraje Internacional?

Los clientes son susceptibles de uno o varios servicios ofrecidos según sus requerimientos:

-   Administración de las Cuentas por Cobrar.

-   Gestión de cobranza de las Cuentas por Cobrar.

-   100% de cobertura de riesgo del comprador (con excepción de la disputa comercial).

-   Acción legal, en caso necesario.

-   Investigación de la solvencia de los compradores en el extranjero.

-   Financiamiento sobre las Cuentas por Cobrar cedidas.

-   Incremento en ventas de exportación al poder ofrecer condiciones competitivas con sus clientes.

-   100% de cobertura contra las posibles pérdidas por falta de pago de los compradores en el extranjero.

-   Liquidez y certeza en sus flujos al descontar sus facturas.

-   Información completa sobre el estatus de las cuentas por cobrar.

-   Costos financieros competitivos.

-   Mejora los indicadores de sus estados financieros por tratarse de Factoraje sin recurso.

-   Información y monitoreo del nivel de riesgo de sus clientes.

-   Comprar bajo condiciones convenientes en “cuenta abierta”.

-   Incrementar sus adquisiciones en mejores términos.

-   Colocar ágilmente las órdenes de compra sin incurrir en retrasos, costos y comisiones en instrumentos como las cartas de crédito, etc.

-   Comunicarse con el Import Factor en su propio idioma.

-   Generar nuevos negocios al entrar en contacto con el Importador.

-   Ofrecer sus servicios de Factoraje a Exportadores con Compradores en un gran número de países alrededor del mundo.

-   Contar con la cobertura de riesgo de crédito de los compradores a través del Import Factor. ¿Quién es FCI?

-   Al Factors Chain International (FCI) se le reconoce como la red de Factoraje más importante en el mundo formada por compañías líderes de Factoraje en diversos continentes, fundada desde 1968 con sede en msterdam, Holanda.

-   Actualmente agrupa a más de 270 miembros en 63 países.

-   Fue creada con la finalidad de desarrollar un marco de Factoraje Internacional que permitiera a las empresas de Factoraje de los países importador y exportador, trabajar en conjunto, así como promover globalmente el uso de Factoraje como el mejor mecanismo para financiar el comercio exterior.

-   Bancomext se convirtió en miembro del FCI en 2010 para contar con los beneficios al pertenecer a esta asociación y brindar este servicio a empresas mexicanas exportadoras e importadoras.

### ¿Qué es Factoraje Internacional de Exportación?

Consiste en una Línea Revolvente, la cual opera electronicamente desde su oficina, brindado los siguientes beneficios:

-   Cobertura del 100% de riesgo de no pago del Comprador en el extranjero.

-   Financiamiento hasta por el 90% del valor de la cuenta por cobrar cedidas.

-   Administración de cuentas por cobrar.

-   Gestión de Cobranza en el extranjero mediante instituciones financieras localizadas en el país del comprador.

-   Ser exportador directo, legalmente constituido en México.

-   Tener al menos 3 exportaciones directas en el año o una anual en los últimos 3 años.

-   Tener buen historial crediticio.

-   No estar en estado técnico de disolución.

-   Ceder la cartera por cobrar de los compradores que sean incorporados al programa.

-   No entran a Factoraje: ventas entre filiales o relacionadas, ni ventas a consignación.

# ¿Cómo funciona el factoraje financiero?

El funcionamiento básico del factoraje implica los siguientes pasos:

i.  Las empresas venden sus facturas pendientes de pago a una entidad de factoraje.

ii. La entidad de factoraje verifica la autenticidad de las facturas y la solvencia de los deudores.

iii. Una vez aprobadas, la entidad de factoraje adelanta un porcentaje del valor de las facturas a las empresas (por lo general, alrededor del 80-90%).

iv. La entidad de factoraje se encarga de cobrar las facturas a los clientes de la empresa.

v.  Cuando los clientes pagan las facturas, la entidad del factoraje retiene una comisión por sus servicios y devuelve el remanente de la empresa.

Cuando la empresa solicita a su cliente la factura por la venta es cuando se puede solicitar el capital. Para que el adelanto suceda, se propone una comisión sobre la línea de crédito, misma que será de utilidad para la empresa que brinda esta solución. En ese momento, y tras negociar las condiciones, se realiza la firma del contrato, en la que ambas partes acuerdan el porcentaje y el plazo en que se deberá realizar el pago del resto de la factura. Por ejemplo, en la forma de factoraje para las pequeñas empresas, usted vende sus cuentas por cobrar a la empresa de factoraje de 60 a 80 % de su valor nominal y recibe esa cantidad en efectivo, en forma anticipada, con el saldo quedando como reserva. Luego, la empresa de factoraje asume la responsabilidad de cobranza.

Cuando los clientes cancelan las facturas, se libera la reserva y la empresa de factoraje le paga el saldo, menos su cargo, el cual puede ser desde el 1% hasta más del 5%, que se llama la tasa de descuento

A la empresa de factoraje le interesa más la capacidad de pago de sus clientes que la calificación de crédito de su negocio. En este sentido, la calidad de sus cuentas por cobrar es lo que vale para la empresa de factoraje y probablemente va a tener un efecto en la tasa de descuento.

## Relación entre Factoraje Financiero e Interés Simple

En el factoraje, el interés que el factor cobra por el adelanto de efectivo suele calcularse de acuerdo con los principios del interés simple. El capital en este caso sería el valor de las facturas adelantadas por la institución financiera. El interés simple se aplica sobre este monto y por el plazo en el que las facturas deban ser pagadas.

Por ejemplo, si una empresa tiene facturas por cobrar con un valor de \$10,000 a 60 días, y el factor cobra un interés del 5% por adelantarlas, el cálculo del interés simple sería:

### Cálculo de Interés

Vamos a calcular el interés I usando la fórmula:

$$
I = 10,000 \times 0.05 \times \left( \frac{60}{360} \right) = 83.33
$$

Esto significa que el factor cobraría \$83.33 como interés por adelantar el monto de las facturas por un período de 60 días.

# ¿Cómo puede usarse el factor financiero?

Para comenzar a hablar sobre el uso que el Factoraje Financiero puede representar, en necesario conocer el objetivo que esta herramienta busca cumplir en las empresas que lo utilizan, así como su clasificación para conocer las distintas operaciones con las cuales puede utilizarse.

El Factoraje Financiero tiene el objetivo de brindar apoyo al capital de una institución reduciendo los ciclos de cobro otorgándole liquidez inmediata, aplicando un respectivo descuento por el uso del servicio. Permite adquirir financiamiento a corto plazo al disponer anticipadamente de las cuentas por cobrar de la empresa, en otras palabras, se adelanta el cobro de una factura, de gran utilidad, ya que permite disponer de inmediato con efectivo que podrá utilizarse para afrontar las necesidades y obligaciones, y promover el crecimiento y la participación en oportunidades de negocio en las que se requiera agilizar el ciclo financiero.

### Clasificación del Factoraje Financiero:

De acuerdo con el Banco Nacional de Comercio Exterior, el factoraje financiero puede clasificarse de la forma:

1.  Por la Implementación del negocio

2.  Por el Compromiso de pago del Proveedor (Factorado).

3.  Por la forma de Cobranza.

4.  Por ubicación.

5.  Por la forma de Implementar el Negocio: Esta forma puede tomar dos modalidades, una en relación con el <u>**cliente**</u> y otra en relación con el <u>**proveedor**</u>.

    • **El factoraje a Clientes o Factoraje Tradiciona**l:

    Es implementado a partir de la relación que establece el factorante (empresa de factoraje) con un proveedor de bienes y servicios. Se hace cuando la factura ya se ha generado y se ha entregado la mercancía vendida, pero antes de aceptar el pago, es decir, el comprador no ha confirmado el pago de la factura de ninguna forma.

    El proveedor que realiza ventas a crédito a sus clientes necesita flujo en su capital de trabajo, por lo tanto, necesita financiamiento cediendo los derechos de sus cuentas por cobrar a la empresa de factoraje quien le otorga la liquidez requerida.

    Aunque el riesgo se asume se relaciona con la calidad crediticia del comprador, ya que se expone al rechazo parcial del pago, por lo que este tipo de factoraje se recomienda que solo esté disponible para proveedores con seguridad crediticia.

    • **El factoraje a Proveedores o Factoraje Inverso**:

    Este tipo de Factoraje nace de la relación de la Empresa de Factoraje con el comprador, el cual cuenta con una buena calidad crediticia, con solvencia moral y económica, el cual, al llevar a cabo sus compras de bienes y servicios, emite documentos de pago en la que formaliza y reconoce su obligación de pago por el total del importe de la factura en una fecha establecida. Por lo que el factorado puede ceder los derechos de cobro al factorante, quien llevará a cabo la cobranza al vencimiento del dicho documento. De esta manera, a partir del comprador, se pueden financiar un factorado.

6.  Por el Compromiso de pago del Proveedor:

    Se refiere al compromiso que el proveedor puede o no existir de ser solidariamente responsable del pago si el comprador no paga la cuenta por cobrar.

    Este punto se encuentra regulado por la Ley General de Títulos y Operaciones de Crédito (LGTOC), la cual establece que este se podrá llevar a cabo en cualquiera de las modalidades siguientes:

    • **Factoraje con Recurso**:

    Se da cuando el factorado quede obligado solidariamente con el deudor, a responder del pago puntual y oportuno de los derechos de crédito transmitidos al factorante (empresa de factoraje financiero).

    • **Factoraje sin Recurso:**

    Es el caso cuando el factorado no quede obligado a responder por el pago de los derechos de crédito transmitidos al factorante (empresa de factoraje financiero).

7.  Por la forma de cobranza.

    • **Cobranza Directa:**

    Es cuando le corresponde al factorante (empresa de factoraje) realizar la cobranza al vencimiento de las cuentas por cobrar directamente ante el deudor, para lo cual deberá notificarles sobre la transmisión de los derechos de crédito.

    • **Cobranza delegada:**

    En este tipo de cobranza el factorado es a quien se le concede llevar a cabo la cobranza de los documentos cedidos, teniendo la obligación de entregar a la empresa de factoraje el cobro efectuado.

    Es decir, se trata de los casos de excepción a la Cobranza Directa, en los que el factorante esta de acuerdo en no llevar a cabo la cobranza y se le delega la responsabilidad al factorado con la obligación de devolver el importe correspondiente recuperado por parte del comprador.

8.  Por la ubicación.

    • **Factoraje Internacional:**

    Este tipo de Factoraje se encarga de atender operaciones internacionales de una empresa. Es de gran ayuda para exportadores ya que pueden cobrar y/o pagar totalmente su cuenta de forma anticipada sin tener que esperar a su vencimiento, brindando la posibilidad de exportación.

    • **Factoraje Domestico:**

    Sucede cuando toda operación relacionada al Factoraje de las cuentas por cobrar sucede dentro de un mismo territorio local. Proveedor y Comprador en el mismo país.

Aquí algunos ejemplos de cómo puede presentarse el uso del Factoraje Financiero en temas de interés público de los cuales tal vez no nos habíamos percatado anteriormente:

1.  "La figura del factoraje financiero en el programa de cadenas productivas de Nacional Financiera (NAFIN) desde la perspectiva de las MIPYMES", por <u>*Matus Castillejos, Devani*</u>

    En la Tesis de licenciatura denominada como "La figura del factoraje financiero en el programa de cadenas productivas de Nacional Financiera (NAFIN) desde la perspectiva de las MIPYMES" realizada por Matus Castillejos, Devani del Centro de Investigación y Docencia Económicas A.C. en la Ciudad de México en el año 2021, se aborda el tema de investigación acerca del impacto de las Micro, Pequeñas y Medianas empresas como fuente de ingreso en la economía nacional y la importancia de fomentar el desarrollo y crecimiento de estas entidades productoras de bienes y servicios por medio de herramientas financieras como lo es el Factoraje Financiero para lograr su continuidad de operación.

    Castillejos menciona en su Introducción los datos que reflejan a las Micro, Pequeñas y Medianas Empresas (MIPYMES) como una gran fuente de ingreso para la Nación Mexicana. Según estos datos del INEGI de 2018, se cubre un gran porcentaje en la tasa de empleo y del Producto Interno Bruto del país gracias a las actividades de estas entidades, por lo que se consideraría fundamental el desarrollo y fortalecimientos de las MIPYMES para impulsar los escenarios económicos de la entidad, para ello será necesario fomentar los mecanismos de financiamiento necesarios para que sigan operando.

    Es por ello que hace mención de la Institución de Banca de Desarrollo Nacional Financiera (NAFIN) y su programa de Cadenas Productivas, implementado por el estado con el objetivo de contribuir a la accesibilidad de las MIPYMES a fondos para operar, tales como los contratos de Factoraje Financiero.

    Para un mejor entendimiento, nos introduce a la explicación del Programa “Cadenas Productivas” como un programa creado por NAFIN en 2001 con la finalidad de otorgar financiamiento y liquidez a las empresas, facilitando el desarrollo de los negocios que toman el papel de proveedores de grandes entidades o dependencias gubernamentales, por lo que el respaldo financiero hacia las MIPYMES representa un propósito para lograr una gran contribución al desarrollo económico del país.

    En el trabajo se describe el proceso de Afiliación que los proveedores pueden llevar a cabo para que, una vez que han sido dados de alta, llevar a cabo la Operación de Factoraje por medio del Sistema Electrónico NAFINET (NAFINET es una plataforma electrónica habilitada por Nacional Financiera para que los proveedores afiliados al programa Cadenas Productivas lleven a cabo las operaciones de factoraje), el cual permite dar de alta los documento de cuentas por cobrar a favor de los proveedores, los cuales podrán ser elegidos según cuales se desean cobrar anticipadamente, con su descuento correspondiente, con esto, se brinda una facilidad al proveedor o Factorado de decidir si realizar la operación tomando en cuenta el costo y otros factores de su información financiera.

    En su conclusión, Castillejos menciona que, si bien el uso de la tecnología y estas nuevas formas de financiamiento para las empresas brinda un gran avance próspero para el desarrollo del país, también es cierto que aún existen algunos aspectos que dificultan que sean mayormente aprovechados o accesibles, tales como la dificultad para la afiliación de las MIPYMES, así como la dificultad de la incorporación empresarial a la formalidad.

    Este ejemplo es valioso ya que nos permite visualizar una problemática existente en el sector económicoproductivo de todo el país y el significado que representa el Factoraje Financiero si este tuviera un mayor alcance.

2.  Sinergia financiera a través del factoraje con cobertura cambiaria, por <u>*Guillermo Pérez Elizundia*</u>

    “El comercio Internacional enfrenta la incertidumbre y la volatilidad que alteran las inversiones y ganancias de transacciones cada vez más dinámicas. El factoraje y los forwards son herramientas financieras estratégicas a la hora de reducir los riesgos en las operaciones”

    En este artículo del Dr. Guillermo Pérez Elizundia de la Coordinación de la Maestría en Alta Dirección de la Facultad de Contaduría y Administración de la UNAM, se hace mención de otra aplicación del Factoraje Financiero en un panorama económico del país en la actualidad.

    El Dr. Pérez menciona que, en el actual entorno económico y comercial, existe una gran variabilidad en los mercados financieros, las organizaciones se encuentran en un constante manejo de liquidez y riesgos. En esta situación, el Factoraje Financiero se visualiza como una herramienta clave para el manejo del flujo efectivo de las empresas, ya que brinda liquidez a corto plazo. Así mismo, los derivados financieros como lo son los Forwards (acuerdos entre dos partes para comprar o vender un activo a un precio fijado en una fecha futura), ofrecen seguridad y protección para situaciones de volatilidad, como lo son las fluctuaciones en el tipo de cambio.

    En el texto se declara que, en el análisis de la economía mexicana, las fluctuaciones del tipo de cambio se han convertido en una constante debido a factores macroeconómicos y políticos, nacionales y mundiales.

    Para un mayor entendimiento, en el artículo se nos presentan varios datos de distintas épocas en México con el porcentaje de apreciación del peso en ese entonces, con lo que resulta fácil para nosotros observar la tasa cambiante, por lo que, ahora podemos interpretar que para aquellos proveedores que utilizan el Factoraje en pesos indexados al dólar, la apreciación del peso representa todo un desafío, ya que en contexto donde se devalúa el peso, al vencimiento de la operación de factoraje, los pagos que recibía solían representar una ganancia cambiaria, sin embargo en contextos de fortalecimiento del peso, esos mismos proveedores sufren perdidas cambiarias.

    Estas fluctuaciones en el tipo de cambio facilitan que nos percatemos de la importancia de la sinergia financiera entre el factoraje y los forwards como estrategias de liquidez, optimizando el capital de trabajo y fortaleciendo la gestión de empresas con operaciones con moneda extranjera.

    “Estas herramientas financieras ofrecen a las empresas estabilidad y previsibilidad financiera en un contexto económico global incierto”.

    En nuestro país, la gran variedad de empresas que existen es de vital importancia en la economía nacional y en el mercado internacional, estas llevan a cabo operaciones de Factoraje, en especial ante fluctuaciones cambiarias que puedan llegar a presentarse, siendo de gran utilidad para las entidades ya que les permite llevar realizar sus operaciones financieras, como el pago de divisas, ya sea en pesos o en dólares.

    Ahora que tenemos claro en qué consiste el factoraje en relación con la volatilidad cambiaria, podemos percibir que un campo donde se aplica esta actividad es en las empresas internacionales de venta al por menor, ya que podrían beneficiarse agilizando sus pagos a proveedores o con un mejor manejo en el flujo de caja, así mismo ayuda en la gestión de riesgos y refuerza la estabilidad financiera.

    Mientras que los forwards permiten la planeación y margen en la diferencia monetaria. s se enfrentan a ciclos más largos y mayores riesgos del mercado internacional, así, con el uso del factoraje, se encuentra la estabilidad y la protección en la vulnerabilidad crediticia en los mercados extranjeros. Mientras que los forwards permiten la planeación y margen en la diferencia monetaria.

    Así, el artículo nos muestra cómo el factoraje y los forwards representan herramientas importantes para encontrar soluciones valiosas y efectivas para enfrentar desafíos de comercio internacional y volatilidad cambiaria, proveyendo a su vez una mayor liquidez a proveedores que facturan en dólares o pesos indexados al dólar

# Bibliografia

### ¿Qué es?

-   <https://www.condusef.gob.mx>

-   [https://www.gob.mx/cms/uploads/attachment/file/111134/CUADERNOSYVIDEOS- SOFOMES.pdf](https://www.gob.mx/cms/uploads/attachment/file/111134/CUADERNOSYVIDEOS-%20SOFOMES.pdf)

-   [https://www.gob.mx/cms/uploads/attachment/file/495174/Necesitas_financiamiento_para_tu_em presa_Conalep.pdf](https://www.gob.mx/cms/uploads/attachment/file/495174/Necesitas_financiamiento_para_tu_em%20presa_Conalep.pdf)

-   <https://afinsafactoring.com/>

    Video

-   <https://www.bancomext.com/wp-content/uploads/2018/11/Cápsula-Libro-Factoraje.mp4> <https://infofactoraje.com.mx/ejemplos-y-formulas-de-factoraje-y-formulas/>

### ¿Cómo funciona?

-   <https://espacioerp.com/factoraje-financiero/>

-   <https://www.mexicoemprende.org.mx/como-funciona-el-factoraje/>

-   <https://mundi.io/exportacion/factoraje-financiero-mexico/>

-   <https://www.apd.es/factoring-finaciero-ejemplos-entenderlo/>

-   <https://www.docusign.com/es-mx/blog/factoraje-financiero>

### ¿Cómo puede usarse?

-   Pérez, G. (2024). Sinergia financiera a través del factoraje con cobertura cambiaria. Negocios Internacionales. [https://www.researchgate.net/profile/Guillermo-PerezElizundia/publication/378654961_Sinergia_financiera_a_traves_del_fac oraje_con_cobertura_cambiaria /links/65e273e2c3b52a1170032d25/Sinergia-financiera-a-traves-del-factoraje-con-coberturacambiaria.pdf](%3Chttps://www.researchgate.net/profile/Guillermo-PerezElizundia/publication/378654961_Sinergia_financiera_a_traves_del_fac%20oraje_con_cobertura_cambiaria%20/links/65e273e2c3b52a1170032d25/Sinergia-financiera-a-traves-del-factoraje-con-coberturacambiaria.pdf)
-   Aguilar, C., Cruz, G., & Gámez, Y. (2010). Factoraje financiero en México: Apoyo cotidiano S.A. de C.V. SOFOM E.N.R.: ejemplo de PyME que ofrece servicio de factoraje financiero en México \[Proyecto de Investigación, Instituto Tecnológico y de Estudios Superiores de Monterrey\]. <https://repositorio.tec.mx/bitstream/handle/11285/629307/33068001091968.pdf>
-   Molina, O. O. (2015). Factoraje financiero como fuente de financiamiento. Fisco actualidades, 4. <https://imcp.org.mx/wpcontent/uploads/2015/08/Fiscoactualidades_julio_n%C3%83%C2%BAm_12.pdf>
-   Matus, D. (2021). La figura del factoraje financiero en el programa de cadenas productivas de Nacional Financiera (NAFIN) desde la perspectiva de las MIPYMES. Recuperado de: <http://hdl.handle.net/11651/4478.>
-   :: AMEFAC - ¿Qué es el Factoraje? ::. <https://www.factoraje.com.mx/que-es-el-factoraje/>
-   Hernandez, M. (2015). Factoraje financiero. [www.academia.edu.https://www.academia.edu/10918102/Factoraje_Financiero](www.academia.edu.https://www.academia.edu/10918102/Factoraje_Financiero)
-   González, J., & Pérez, G. (2022). FACTORAJE. En IPADE. <https://www.researchgate.net/profile/GuillermoPerez-Elizundia/publication/367088728_Factoraje/links/63c0cbc6ef57e61a611236fa/Factoraje.pdf>
-   González, F. (2018). FACTORAJE FINANCIERO. <https://www.bancomext.com/wpcontent/uploads/2018/12/Factoraje_Libro_digital.pdf>
